In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv("Logistic_Iris.csv")
df.head()

Sepal Length  Sepal Width  Petal Length  Peatal Width      Species
0           5.1          3.5           1.4           0.2  Iris-setosa
1           4.9          3.0           1.4           0.2  Iris-setosa
2           4.7          3.2           1.3           0.2  Iris-setosa
3           4.6          3.1           1.5           0.2  Iris-setosa
4           5.0          3.6           1.4           0.2  Iris-setosa

In [6]:
x=df.iloc[:,[0,1,2,3]].values
y=df.iloc[:,4].values

In [8]:
xtr,xts,ytr,yts = train_test_split(x,y,train_size = 0.25)
gnb = GaussianNB()
gnb.fit(xtr,ytr)
y_pred=gnb.predict(xts)

In [17]:
acc_gnb = accuracy_score(yts,y_pred)*100
print("The Accuracy score for Gaussian NB is ",acc_gnb)


The Accuracy score for Gaussian NB is  94.69026548672566


In [28]:
cm=confusion_matrix(yts,y_pred)
base_cls=GaussianNB()
bag=BaggingClassifier(base_estimator=base_cls,n_estimators=100,random_state = 0)
bag.fit(xtr,ytr)
print("\n\nThe Confusion Matrix:\n",cm)



The Confusion Matrix:
 [[37  0  0]
 [ 0 33  2]
 [ 0  4 37]]


In [26]:
results=model_selection.cross_val_score(Bag,xts,yts,cv=10).mean()*100
print("Accuracy",results)

Accuracy 94.62121212121211
